### ISSUE TITLE
Impossible to logout. Stuck in a loop.

### ISSUE THREAD

**Issue by bedwardly-down** [fr0tt/benotes#15] opened 2021-06-26 08:03 UTC
I just setup everything following your instructions and used Postgresql as my DB. Selecting logout takes me back to the main screen as if I'm automatically logging back in. I'm not using a reverse proxy at all and serving straight from the public folder in my copy of the git repo along with having proper permissions setup on the storage folder.

## Steps to Reproduce
* Setup on server
* Create initial user
* Login to Benotes
* Create random things
* Attempt to logout
* Loop back to main app page

## Server Info
OS: Gentoo
Node: 14.16.1
PHP: 7.4.19
Serving Software: Caddy V2

## Caddyfile

``` 
server-domain-name {
	log {
		output file /var/log/caddy/note.log
		format single_field common_log
		level info
	}
	root * /My-Home/git/benotes/public
	php_fastcgi 127.0.0.1:36500
	file_server

	tls my-email
}
```

When I try to logout, my log shows this at that moment: 
`[26/Jun/2021:08:06:33 +0000] "GET /service-worker.js HTTP/2.0" 200 23072` 

I can provide further information if needed. Thanks

**Comment by bedwardly-down** [comment] 2021-06-26 13:21
This issue seems to be Firefox related, too. I have a laptop running Arch Linux, an iPhone 11 and a OnePlus 7T Pro all having this issue only on Firefox. When running on Chrome or Safari, I can log out perfectly fine.

**Comment by fr0tt** [comment] 2021-06-26 19:40
Thanks for your issue and your detailed explanation !

It took me a while to reproduce your bug. I tried different devices, different servers and different browsers but everything worked just fine. However at last I figured out how to reproduce it.

You need to use:
- firefox
- not a private window
- not deleting cookies after closing firefox

Only if you meet all three requirements you will see this kind of weird behaviour.

So my guess is, it's cookie related. I will look into it and let you know if I know more or have fixed it.

**Comment by bedwardly-down** [comment] 2021-06-26 23:31
Thanks for getting back to me on that. What’s interesting is that my previous app that was the same subdomain randomly bleeds through, despite me removing it from my server. I’ve also noticed that running through incognito mode solves the issue completely (despite closing out the moment I leave Firefox on mobile, making bookmark saving almost impossible).

**Comment by fr0tt** [comment] 2021-06-27 10:41
Sure of course. It's rather weird that you see something of your old app, maybe it's still in your browsers cache ? (e.g. the favicon)
Indeed, using incognito mode seems to work just fine (that's why it was difficult for me to reproduce your problem). 

So I hope I could successfully fix this problem. 
Try pulling the latest commit and let me know if the problem is solved or not.
I didn't change anything cookie related and my fix should actually not care if you use incognito or not but it still seems to do the trick somehow.

**Comment by bedwardly-down** [comment] 2021-06-27 13:25
Alright. Looks like your changes fixed the issue and clearing my mobile cache and restarting my server so far killed off the bleeding through (but it may come back at some point). Here's to hoping.

**Comment by fr0tt** [comment] 2021-06-27 22:22
Great ! Then I'm going to close this issue. 
Feel free to reopen it if something happens.

**Closed by fr0tt** 2021-06-27 22:22 UTC
Labels: bug
